/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package flightschedulerkaixuanmengkbm5393;

/**
 *
 * @author paulm
 */
import java.sql.Date;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;

public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    private List<Flight> flightlist;
    private List<Date> datelist;
    
    public NewJFrame() {
        initComponents();
        flightlist = FlightList.getFlightList();
        datelist = DateList.getDateList();
        AddFlightComboBox();
        AddDateComboBox();
        AddNameComboBox();
        SuccessA.setVisible(false);
        SuccessB.setVisible(false);
        BookDisplay.setEditable(false);
        Display.setEditable(false);
        CancelDisplay.setEditable(false);
        DropDisplay.setEditable(false);
    }
    
    private void AddFlightComboBox() {
        FlightBox.removeAllItems();
        FlightBox1.removeAllItems();
        DropFlightList.removeAllItems();
        flightlist = FlightList.getFlightList();
        flightlist.forEach((flight) -> {
            FlightBox.addItem(flight.getFlightNum());
            FlightBox1.addItem(flight.getFlightNum());
            DropFlightList.addItem(flight.getFlightNum());
        });
    }
    private void AddDateComboBox() {
        DateBox.removeAllItems();
        DateBox1.removeAllItems();
        cancelDate.removeAllItems();
        datelist = DateList.getDateList();
        datelist.forEach((d) -> {
            DateBox.addItem(d.toString());
            DateBox1.addItem(d.toString());
            cancelDate.addItem(d.toString());
        });
    }
    private void AddNameComboBox() {
        cancelName.removeAllItems();
        Cname.removeAllItems();
        List<Book>NameList=BookingList.getBookList();
        NameList.addAll(WaitList.getWaitList());
        NameList.forEach((b) -> {
            cancelName.addItem(b.getName());
            Cname.addItem(b.getName());
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Drop = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        CustomerName = new javax.swing.JTextField();
        DateBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        FlightBox = new javax.swing.JComboBox<>();
        BOOK = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        BookDisplay = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Search = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Display = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        DateBox1 = new javax.swing.JComboBox<>();
        SbyName = new javax.swing.JCheckBox();
        WL_checkBox = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        FlightBox1 = new javax.swing.JComboBox<>();
        Cname = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        FlightN = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        NofSeat = new javax.swing.JTextField();
        AddFlight = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        DateAdded = new javax.swing.JTextField();
        AddDate = new javax.swing.JButton();
        SuccessA = new javax.swing.JLabel();
        SuccessB = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cancelName = new javax.swing.JComboBox<>();
        cancelDate = new javax.swing.JComboBox<>();
        CancelButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        CancelDisplay = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        DropFlightList = new javax.swing.JComboBox<>();
        DropButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        DropDisplay = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setText("Flight Scheduler");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Name: ");

        CustomerName.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        CustomerName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CustomerNameMouseClicked(evt);
            }
        });

        DateBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        DateBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateBoxActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Date: ");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Flight: ");

        FlightBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        BOOK.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BOOK.setText("BOOK");
        BOOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOOKActionPerformed(evt);
            }
        });

        Clear.setText("Clear");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });

        BookDisplay.setColumns(20);
        BookDisplay.setRows(5);
        jScrollPane4.setViewportView(BookDisplay);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(5, 5, 5)
                        .addComponent(CustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BOOK, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FlightBox, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DateBox, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(DateBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(FlightBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addComponent(BOOK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Clear)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Drop.addTab("Book", jPanel1);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Customer Name:");

        Search.setText("Search");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });

        Display.setEditable(false);
        Display.setColumns(20);
        Display.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Display.setRows(5);
        jScrollPane1.setViewportView(Display);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Date: ");

        DateBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        DateBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateBox1ActionPerformed(evt);
            }
        });

        SbyName.setText("Search By Name");

        WL_checkBox.setText("Wait List");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Flight: ");

        FlightBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Cname.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Cname, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(DateBox1, 0, 129, Short.MAX_VALUE)
                                    .addComponent(FlightBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SbyName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(WL_checkBox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Search)))
                .addGap(57, 57, 57))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SbyName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Cname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DateBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addComponent(Search, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(FlightBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WL_checkBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );

        Drop.addTab("Status", jPanel2);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setText("Add a Flight: ");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setText("Flight number: ");

        FlightN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FlightNMouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setText("number of Seat: ");

        NofSeat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NofSeatMouseClicked(evt);
            }
        });
        NofSeat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NofSeatActionPerformed(evt);
            }
        });

        AddFlight.setText("Add Flight");
        AddFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddFlightActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel11.setText("Add a Date: ");

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setText("Date: ");

        DateAdded.setText("yyyy-mm-dd");
        DateAdded.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DateAddedMouseClicked(evt);
            }
        });
        DateAdded.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateAddedActionPerformed(evt);
            }
        });

        AddDate.setText("Add Date");
        AddDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddDateActionPerformed(evt);
            }
        });

        SuccessA.setText("Success");

        SuccessB.setText("Success");

        jLabel13.setText("Format:  yyyy-mm-dd");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(FlightN)
                                    .addComponent(NofSeat)
                                    .addComponent(DateAdded, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                                .addGap(38, 38, 38)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(SuccessA, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(AddFlight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(AddDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(jLabel13)))))
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(SuccessB)
                .addGap(66, 66, 66))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel8)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FlightN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(NofSeat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(jLabel11))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(AddFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SuccessA, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(DateAdded, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddDate, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SuccessB)
                    .addComponent(jLabel13))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        Drop.addTab("Add", jPanel5);

        jLabel14.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel14.setText("Customer Name: ");

        jLabel15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel15.setText("Date of Flight: ");

        cancelName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cancelDate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        CancelButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        CancelDisplay.setColumns(20);
        CancelDisplay.setRows(5);
        jScrollPane2.setViewportView(CancelDisplay);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cancelName, 0, 122, Short.MAX_VALUE)
                    .addComponent(cancelDate, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(CancelButton)
                .addGap(43, 43, 43))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(cancelName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(cancelDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                .addContainerGap())
        );

        Drop.addTab("Cancel", jPanel3);

        jLabel16.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel16.setText("Flight List: ");

        DropFlightList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        DropButton.setText("Drop");
        DropButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DropButtonActionPerformed(evt);
            }
        });

        DropDisplay.setColumns(20);
        DropDisplay.setRows(5);
        jScrollPane3.setViewportView(DropDisplay);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DropFlightList, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(DropButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(DropFlightList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DropButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addContainerGap())
        );

        Drop.addTab("Drop", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(221, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(200, 200, 200))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Drop, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Drop, javax.swing.GroupLayout.PREFERRED_SIZE, 311, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DateBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DateBox1ActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed

        Display.setText("");
        String Customer_Name=Cname.getSelectedItem().toString();
        if (SbyName.isSelected()==false) {
            Date DateBooked=Date.valueOf(DateBox1.getSelectedItem().toString());
            String flightBooked=FlightBox1.getSelectedItem().toString();
            List<Book> result=new ArrayList<Book>();
            if (WL_checkBox.isSelected()==false) {
                result=BookingList.findByFlightDate(DateBooked, flightBooked);
            }

            else {
                result=WaitList.findByFlightDate(DateBooked,flightBooked);

            }
            if (result.size()==0) {
                Display.append("No Result");
            }
            else {
            for(Book b: result) {
                Display.append(String.format("Customer: %s\n\n"
                    + "Date: %s\n" + "Flight: %s\n"+"TimeStamp: %s\n\n\n",
                    b.getName(),
                    b.getDate().toString(),
                    b.getFlight(),
                    b.getTimeStamp().toString()));
            }
        }
        }
        else {
            List<Book> result=new ArrayList<Book>();
            result=BookingList.findByName(Customer_Name);
            if (result.isEmpty()) {
                result=WaitList.findByName(Customer_Name);
                if (result.isEmpty()) {
                    Display.setText("No result");
                }
                else {
                    for(Book b: result) {
                        Display.append(String.format("Customer(%s) is on WaitList:\n\n"
                            + "Date: %s\n" + "Flight: %s\n"+"TimeStamp: %s\n\n\n",
                            Customer_Name,
                            b.getDate().toString(),
                            b.getFlight(),
                            b.getTimeStamp().toString()));
                }
            }
        }
        else {
            for(Book b: result) {
                Display.append(String.format("Customer(%s) has trip:\n\n"
                    + "Date: %s\n" + "Flight: %s\n"+"TimeStamp: %s\n\n\n",
                    Customer_Name,
                    b.getDate().toString(),
                    b.getFlight(),
                    b.getTimeStamp().toString()));
        }
        }
        }
    }//GEN-LAST:event_SearchActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        CustomerName.setText("");
        flightlist=FlightList.getFlightList();
        datelist=DateList.getDateList();
        AddFlightComboBox();
        AddDateComboBox();
        BookDisplay.setText("");
    }//GEN-LAST:event_ClearActionPerformed

    private void BOOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOOKActionPerformed
        BookDisplay.setText("");
        Date DateBooked=Date.valueOf(DateBox.getSelectedItem().toString());
        String FlightSelected=FlightBox.getSelectedItem().toString();
        if (BookingList.getEmptySeats(DateBooked, FlightSelected)>0) {
            BookingList.newBook(CustomerName.getText(), DateBooked, FlightSelected);

            Timestamp currentTimeStamp=new Timestamp(Calendar.getInstance().getTime().getTime());
            BookDisplay.append(String.format("Booked Successfully\nBooking information:\n\n"
                    + "Customer Name: %s\n"
                    + "Date: %s\n"
                    + "Flight: %s\n"
                    + "Timestamp: %s\n\n", CustomerName.getText(),DateBooked, FlightSelected,currentTimeStamp));
        }
        else {
            WaitList.addWaitList(CustomerName.getText(), DateBooked, FlightSelected);
            Timestamp currentTimeStamp=new Timestamp(Calendar.getInstance().getTime().getTime());
            BookDisplay.append(String.format("Added to Wait List\nWait List information:\n\n"
                    + "Customer Name: %s\n"
                    + "Date: %s\n"
                    + "Flight: %s\n"
                    + "Timestamp: %s\n\n", CustomerName.getText(),DateBooked, FlightSelected,currentTimeStamp));
        }
        AddNameComboBox();
    }//GEN-LAST:event_BOOKActionPerformed

    private void DateBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DateBoxActionPerformed

    private void AddFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddFlightActionPerformed
        String flight=FlightN.getText();
        int seat=Integer.valueOf(NofSeat.getText());
        if (!FlightList.findFlight(flight)) {
            FlightList.addFlight(flight, seat);
            SuccessA.setText("Success");
            flightlist = FlightList.getFlightList();
            AddFlightComboBox();
            }
        else {
            SuccessA.setText("Already exist");
        }
        SuccessA.setVisible(true);
    }//GEN-LAST:event_AddFlightActionPerformed

    private void AddDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddDateActionPerformed
        Date newDate;
        int result;
        try {
            newDate=Date.valueOf(DateAdded.getText());
            result=DateList.addDate(newDate);
            if (result>0){
                SuccessB.setText("Success");
                datelist = DateList.getDateList();
                AddDateComboBox();
                }
            else {
                SuccessB.setText("Already exist");
            }
            SuccessB.setVisible(true);
        }
        catch (IllegalArgumentException e) {SuccessB.setText("Invalid input");
            SuccessB.setVisible(true);
        }
    }//GEN-LAST:event_AddDateActionPerformed

    private void DateAddedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateAddedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DateAddedActionPerformed

    private void NofSeatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NofSeatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NofSeatActionPerformed

    private void DateAddedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DateAddedMouseClicked
        SuccessB.setVisible(false);
        if ("yyyy-mm-dd".equals(DateAdded.getText())) {
            DateAdded.setText("");}
    }//GEN-LAST:event_DateAddedMouseClicked

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        
        CancelDisplay.setText("");
        String Cname=cancelName.getSelectedItem().toString();
        Date Fdate=Date.valueOf(cancelDate.getSelectedItem().toString());
        Book book=BookingList.deleteBook(Cname,Fdate);
        if (book==null) {
            CancelDisplay.append(String.format("Invalid input.%n Customer: %s does not have any flight on %s\n", 
                    Cname, Fdate.toString()));
        }
        else{
            CancelDisplay.append(String.format("Successfully delete booking for customer: %s\n"
                    + " for Flight: %s\n"
                    + " on %s\n\n\n", book.getName(),book.getFlight(),book.getDate().toString()));
        Book newbook=WaitList.updatetoBook(book);
        if (newbook!=null) {
            BookingList.newBook(newbook.getName(), newbook.getDate(), newbook.getFlight());
            CancelDisplay.append(String.format("Customer (%s) is automatically booked from Wait List with: \n"
                    + "Date: %s\n" + "Flight: %s\n"+"TimeStamp: %s\n\n\n",
                    newbook.getName(),
                    newbook.getDate().toString(),
                    newbook.getFlight(),
                    newbook.getTimeStamp().toString()));
        }
        }
        AddNameComboBox();
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void DropButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DropButtonActionPerformed
        DropDisplay.setText("");
        String dropflight=DropFlightList.getSelectedItem().toString();
        int j=FlightList.dropFlight(dropflight);
        DropDisplay.append(String.format("drop Flight: %s successfully\n\n", dropflight));     
        List<Book> booklist=BookingList.findbyFlight(dropflight);
        int Nrow=BookingList.dropbyFlight(dropflight);
        List<Flight> FList=FlightList.getFlightList();
        List<Book> newBookList=new ArrayList<>();;
        boolean booked=false;
        List<String> faillist=new ArrayList<>();;
        if (Nrow>0) {
            for (Book book: booklist) {
                for (Flight F:FList) {
                    if (BookingList.getEmptySeats(book.getDate(), F.getFlightNum())>0) {
                        BookingList.newBook(book.getName(),book.getDate(), F.getFlightNum());
                        booked=true;
                        Timestamp currentTimeStamp=new Timestamp(Calendar.getInstance().getTime().getTime());
                        DropDisplay.append(String.format("Customer: %s is rebooked with:\n"
                                + "Date: %s\n" + "Flight: %s\n"+"TimeStamp: %s\n\n",book.getName(),
                                book.getDate().toString(),
                                F.getFlightNum(),
                                currentTimeStamp));
                        break;
                    }
                }
                if (booked==false) {
                    faillist.add(book.getName());
                }
                booked=false;
            }
            if (faillist.size()>0) {
                DropDisplay.append("Customers: ");
                for (String S: faillist) {
                    DropDisplay.append(String.format("%s, ",S));
                }
                DropDisplay.append("fail to rebook due to lack of seats\n\n");
            }
            List<Book> droppedwaitlist=WaitList.findbyFlight(dropflight);
            int k=WaitList.dropbyFlight(dropflight);
            if (k>0) {
                DropDisplay.append("Customer: ");
                for (Book B: droppedwaitlist) {
                    DropDisplay.append(String.format("%s, ",B.getName()));
                }
                DropDisplay.append(String.format("are dropped from waitlist because Flight %s is dropped\n", dropflight));
                
            }
            else {
                DropDisplay.append("No Booking from Wait List is dropped");
            }
        }
        else {
            DropDisplay.append("No Customer need to rebook");
        }
        AddFlightComboBox();
        AddDateComboBox();
        AddNameComboBox();
    }//GEN-LAST:event_DropButtonActionPerformed

    private void FlightNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FlightNMouseClicked
       SuccessA.setVisible(false);
    }//GEN-LAST:event_FlightNMouseClicked

    private void NofSeatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NofSeatMouseClicked
        SuccessA.setVisible(false);
    }//GEN-LAST:event_NofSeatMouseClicked

    private void CustomerNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomerNameMouseClicked

    }//GEN-LAST:event_CustomerNameMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new NewJFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddDate;
    private javax.swing.JButton AddFlight;
    private javax.swing.JButton BOOK;
    private javax.swing.JTextArea BookDisplay;
    private javax.swing.JButton CancelButton;
    private javax.swing.JTextArea CancelDisplay;
    private javax.swing.JButton Clear;
    private javax.swing.JComboBox<String> Cname;
    private javax.swing.JTextField CustomerName;
    private javax.swing.JTextField DateAdded;
    private javax.swing.JComboBox<String> DateBox;
    private javax.swing.JComboBox<String> DateBox1;
    private javax.swing.JTextArea Display;
    private javax.swing.JTabbedPane Drop;
    private javax.swing.JButton DropButton;
    private javax.swing.JTextArea DropDisplay;
    private javax.swing.JComboBox<String> DropFlightList;
    private javax.swing.JComboBox<String> FlightBox;
    private javax.swing.JComboBox<String> FlightBox1;
    private javax.swing.JTextField FlightN;
    private javax.swing.JTextField NofSeat;
    private javax.swing.JCheckBox SbyName;
    private javax.swing.JButton Search;
    private javax.swing.JLabel SuccessA;
    private javax.swing.JLabel SuccessB;
    private javax.swing.JCheckBox WL_checkBox;
    private javax.swing.JComboBox<String> cancelDate;
    private javax.swing.JComboBox<String> cancelName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
